version: '3.7'
services:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - mongo
    env_file: .env