version: '3.7'

services:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  server:
    build: ./
    ports:
      - 8081:8081
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - mongo
    env_file: .env