version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
  server:
    container_name: server
    restart: always
    build: .
    env_file: .env
    ports:
      - 3000:3000
    external_links:
      - mongo
    depends_on:
      - mongo